name: Build and push Container
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Chechout Code
    - uses: docker/build-push-action@v1.1.0
      name: Build Container
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: src/
        registry: ghcr.io
        repository: golubiev-ievgen/az-dns-forwarder/az-dns-forwarder
        tags: latest
        tag_with_sha: true
        add_git_labels: true
